### ISSUE TITLE
could you support -1 value in settings.conf? -1 means infinite, thanks

### ISSUE THREAD

**Issue by kokqi** [4drian3d/EpicGuard#118]
for example
    limit=-1 
    should allow infinite accounts

**Comment by 4drian3d** [comment]
If you mean disabling the check or having it only run in attack mode, in each check there is a configuration for that

**Comment by 4drian3d** [comment]
If you mean disabling the check or having it only run in attack mode, in each check there is a configuration for that

**Comment by kokqi** [comment]
# Limit of accounts connected per one IP address without any attack happening.
    # A list of accounts per IP is tracked and stored in the database.
    limit=10000
    
    
    no there's no way to disable the ip limit per ip check with -1 or an option to disable it

**Comment by 4drian3d** [comment]
![image](https://github.com/4drian3d/EpicGuard/assets/68704415/bafb24be-90f8-4c3a-bd1f-c705d681ea5d)
