### ISSUE TITLE
Velocity console spammed by UpdateChecker

### ISSUE THREAD

**Issue by Straikerinos** [4drian3d/EpicGuard#56]
1) If update checker is disabled (or enabled..), it's still checking.
2) Console is spammed by errors for NumberFormatException.

Velocity version: 3.2.0 build 254
EpicGuard: 7.4.1

Error: https://pastebin.com/YexiSYPZ

**Comment by 4drian3d** [comment]
You shouldn't get that error anymore, for some reason, GitHub added a line break when I edited the version in the VERSION.txt file (No need to update)
About the update checker, I just fixed the bug that didn't take into account the configuration, if you want to use that version, you can try https://github.com/4drian3d/EpicGuard/actions/runs/4984009832

**Comment by Straikerinos** [comment]
Problem is solved, great job!
