### ISSUE TITLE
Changing username can trigger too many accounts per IP address

### ISSUE THREAD

**Issue by Avenred** [4drian3d/EpicGuard#60]
Even with just two Minecraft accounts, someone can trigger the account-limit-check. By changing your username, each username change is a new 'account'.
For example, a user could have `Account1` and `Account2`. If `Account2` changes username to `Account3`, there will now be 3 accounts all tied to 1 IP address. Now, if `Account3` changes username to `Account4`, there will be four usernames tied to 1 IP.
Looking through the config, I don't see any way to tie the number of accounts to UUIDs instead of usernames. I'm assuming that storing UUIDs per IP address instead of usernames may fix this issue.

**Comment by 4drian3d** [comment]
If a UUID limit is implemented instead of Nickname it would only work for clients 1.19.1 and higher and only for Paper and Waterfall (_Velocity has a [pull request](https://github.com/PaperMC/Velocity/pull/1009) that adds that_)

Also, I find it very strange that someone changes his nickname in several accounts with the same IP in the same day

**Comment by kyngs** [comment]
> If a UUID limit is implemented instead of Nickname it would only work for clients 1.19.1 and higher and only for Paper and Waterfall (_Velocity has a [pull request](https://github.com/PaperMC/Velocity/pull/1009) that adds that_)
> 
> Also, I find it very strange that someone changes his nickname in several accounts with the same IP in the same day

Wouldn't using UUID in the PreLogin event be dangerous? The GameProfileRequestEvent is called *after* PreLoginEvent

**Comment by 4drian3d** [comment]
Implemented a new account limit in https://github.com/4drian3d/EpicGuard/commit/ef6ade356d5f053d7143679e564e85e6f853f0f3
