### ISSUE TITLE
Some suggestion?

### ISSUE THREAD

**Issue by FallenCrystal** [4drian3d/EpicGuard#63]
## 1: [Waterfall] Use ConnectionInitEvent

u maybe know that. it can help you quickly disconnect connection `on PipelineUtils`.

### why use this? Connection throttle is very powerful.

most people use using something like mcstorm or renting their own hosting to attack servers. those socket bots dont care what reason u use to disconnect them or want u to check they username.

so we can disconnect from them as quickly as possible. Instead of block them all on PreLoginEvent. this also helps the server accept more connections and can prevents them from dropping invalid packets to the proxy.

**[Unverified]** and i remember "call `ConnectionInitEvent`" this step is behind the HAProxy decoder. that mean they can work with proxies.  `Connection throttle` and `ClientConnectionEvent` cannot to do that.

### need attention?

  - `ConnectionInitEvent` exists only with waterfall. but i think have a reason them say that "support waterfall" instead of "support bungeecord and forks.
  - some forks may deactivate this event. so consider making that can configurable(only boolean?). we probably wouldnt want them to edit it without knowing what it was. (if they just think that using more antibot will bring better results. then they are no different from idiots.)

## 2: [General] IPSet & IPTables

> but for velocity this may be useless. but its especially useful on servers like Paper.

servers such as Paper drop too many connections when they suffer a slightly stronger attack. their throttle even looks like a decoration.
i dont think any1 would want to do too much on those servers for antibot. IPSet and IPTables seem to be the best solution.

> i dont recommend making those servers public directly instead use a proxy like velocity.

> we cant do much with windows and free/cheap hosting. 
> if their host can. blocking on L4 is a cool thing. although manipulating IPSet using the command line will also **consume your CPU**. 
> not everyone will run as root. and on a more powerful host. using IPSet to face attacks on so many IPs can even be counterproductive. i cant weigh that. it depends.

## 3: [General] reduce console spam

most people dont care at what speed robots are coming at them. they may also not care they server is under attack. they just want to see if there's a problem with their server. reducing things like this can largely preserve CPU usage.

> maybe we dont need to care much about that. at least better than printing spam in the console that says "Enabling attack-mode". (it was a very old issue, i just filtered it in the console filter. im also glad it was fixed. although i dont use epicguard much now)

## ure not very interested in this but not veto?

if I have time i can consider forking it myself but i cant promise i can help. i write code that doesnt follow any code style. and sometimes i will stupid. i just want to do something with my abilities. thats all.

**Comment by 4drian3d** [comment]
1. I am not really interested in maintaining the Waterfall module (_I even put a deprecation message in the last update)_. Although if someone makes a pull request adding a listener for that event and it is compatible with the current system, I may consider to merge it.
2. About the IPTables issue, there are configuration guides on how to configure good IPTables rules, I don't think it is so necessary for EpicGuard to integrate this, although it could be done in the future.
3. In the next update I will add a way to disable certain messages. Although using the EpicGuard log filter or with [LogFilter](https://modrinth.com/plugin/logfilter) you can filter these messages.

For next time, try to make an issue for each topic
